### Get all books
GET http://localhost:3000/books

### Add a new book
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Clean Code",
  "author": "Robert C. Martin"
}

### Update a book (id = 2)
PUT http://localhost:3000/books/2
Content-Type: application/json

{
  "title": "The Alchemist - Updated"
}

### Delete a book (id = 1)
DELETE http://localhost:3000/books/1
